// $Id: memory.asm,v 1.1 2007-05-29 00:36:12 heroine Exp $
lea    (%ecx,%eax,1),%eax
lea    (%edx,%eax,1),%eax
lea    (%ebx,%eax,1),%eax
lea    (%esi,%eax,1),%eax
lea    (%edi,%eax,1),%eax
lea    (%ebx,%ecx,1),%eax
lea    (%ebx,%edx,1),%eax
lea    (%edi,%edx,1),%eax
lea    (%ebx,%esi,1),%eax
lea    (%eax,%eax,2),%eax
lea    (%edx,%edx,2),%eax
lea    (%ebx,%ebx,2),%eax
lea    (%edi,%edi,2),%eax
lea    (%eax,%eax,4),%eax
lea    (%edx,%eax,4),%eax
lea    (%edx,%edx,4),%eax
lea    (%ebx,%ebx,4),%eax
lea    (%esi,%esi,4),%eax
lea    (%ebx,%eax,8),%eax
lea    0x0(,%ecx,8),%eax
lea    0x0(,%edx,8),%eax
lea    0x805b880(,%ebx,8),%eax
lea    0x0(,%esi,8),%eax
lea    (%eax,%edx,1),%ecx
lea    (%edx,%ebx,1),%ecx
lea    (%edx,%esi,1),%ecx
lea    (%edi,%esi,1),%ecx
lea    (%ebx,%eax,4),%ecx
lea    (%eax,%edx,4),%ecx
lea    0x0(,%ebx,4),%ecx
lea    0x0(,%edi,4),%ecx
lea    (%eax,%ecx,1),%edx
lea    (%eax,%eax,2),%edx
lea    (%edx,%edx,2),%edx
lea    0x0(,%ecx,4),%edx
lea    (%edx,%edx,4),%edx
lea    (%edi,%edx,4),%edx
lea    (%ebx,%ebx,4),%edx
lea    (%esi,%eax,8),%edx
lea    (%eax,%edx,8),%edx
lea    (%edx,%eax,1),%ebx
lea    (%edi,%edx,1),%ebx
lea    (%edx,%eax,2),%ebx
lea    (%eax,%edx,2),%ebx
lea    (%edi,%ecx,4),%ebx
lea    (%edx,%ebx,4),%ebx
lea    (%ebx,%eax,8),%ebx
lea    0x0(,%ecx,8),%ebx
lea    (%ecx,%eax,1),%esi
lea    (%ebx,%ecx,1),%esi
lea    (%ecx,%edx,1),%esi
lea    (%edx,%edi,1),%esi
lea    (%edx,%eax,4),%esi
lea    0x0(,%ebx,8),%esi
lea    (%ebx,%eax,1),%edi
lea    (%esi,%eax,1),%edi
lea    (%eax,%edx,8),%edi
lea    0xffffffff(%eax),%eax
lea    0xffffffff(%edx),%eax
lea    0x8(%ebx),%eax
lea    0x14(%ebx),%eax
lea    0x15(%ebx),%eax
lea    0x1(%ecx,%eax,1),%eax
lea    0x2(%ecx,%eax,1),%eax
lea    0x1(%edx,%eax,1),%eax
lea    0xc(%edi,%eax,1),%eax
lea    0x1(%eax,%ebx,1),%eax
lea    0x20(%eax,%ebx,1),%eax
lea    0x23(%esp),%eax
lea    0x2f(%esp),%eax
lea    0x2(%eax,%edi,1),%eax
lea    0xffffffd0(%eax,%edx,2),%eax
lea    0x18(%ebp),%eax
lea    0xffffff90(%ebp),%eax
lea    0xffffff9c(%ebp),%eax
lea    0xffffffa2(%ebp),%eax
lea    0xffffffb7(%ebp),%eax
lea    0xffffffbf(%ebp),%eax
lea    0xffffffca(%ebp),%eax
lea    0xffffffcc(%ebp),%eax
lea    0xffffffd8(%ebp),%eax
lea    0xffffffe0(%ebp),%eax
lea    0xffffffe3(%ebp),%eax
lea    0xffffffe8(%ebp),%eax
lea    0xffffffec(%ebp),%eax
lea    0xfffffff0(%ebp),%eax
lea    0xfffffff4(%ebp),%eax
lea    0x7c(%esi),%eax
lea    0xffffffff(%edi),%eax
lea    0x1(%eax),%ecx
lea    0x64(%eax),%ecx
lea    0x1(%edx),%ecx
lea    0x64(%edx),%ecx
lea    0x1(%ebx),%ecx
lea    0x4(%ecx,%edx,1),%ecx
lea    0x4(%esp),%ecx
lea    0x1(%eax,%esi,1),%ecx
lea    0xffffffa2(%ebp),%ecx
lea    0xffffffb7(%ebp),%ecx
lea    0xffffffbf(%ebp),%ecx
lea    0xffffffcc(%ebp),%ecx
lea    0xffffffe5(%ebp),%ecx
lea    0xffffffe6(%ebp),%ecx
lea    0xffffffe8(%ebp),%ecx
lea    0xffffffec(%ebp),%ecx
lea    0xfffffff0(%ebp),%ecx
lea    0xfffffff4(%ebp),%ecx
lea    0x1(%edi),%ecx
lea    0x1(%eax),%edx
lea    0xffffffe8(%eax),%edx
lea    0xfffffffe(%eax),%edx
lea    0xffffffcc(%ebp),%edx
lea    0xffffffd8(%ebp),%edx
lea    0xffffffdf(%ebp),%edx
lea    0xffffffe4(%ebp),%edx
lea    0xffffffe6(%ebp),%edx
lea    0xffffffe7(%ebp),%edx
lea    0xffffffec(%ebp),%edx
lea    0xfffffff0(%ebp),%edx
lea    0x1(%eax),%ebx
lea    0x7(%eax),%ebx
lea    0x13(%edx),%ebx
lea    0xffffffff(%edx,%eax,1),%ebx
lea    0xffffffff(%ecx,%ebx,1),%ebx
lea    0xffffffc8(%ebp),%ebx
lea    0xffffffca(%ebp),%ebx
lea    0xffffffcc(%ebp),%ebx
lea    0xffffffd0(%ebp),%ebx
lea    0xffffffd8(%ebp),%ebx
lea    0xfffffff0(%ebp),%ebx
lea    0x1(%esi),%ebx
lea    0x1(%edi),%ebx
lea    0xfffffff4(%ebp),%esp
lea    0x1(%eax),%esi
lea    0x7(%eax),%esi
lea    0x13(%eax),%esi
lea    0xffffff80(%eax),%esi
lea    0xfffffff2(%eax),%esi
lea    0xffffffff(%eax),%esi
lea    0x1(%ebx),%esi
lea    0xffffffff(%ebx,%eax,1),%esi
lea    0x0(%esi),%esi
lea    0xffffff9c(%eax,%edi,1),%esi
lea    0xffffffd0(%ebp),%esi
lea    0xffffffed(%ebp),%esi
lea    0x0(%esi),%esi
lea    0x1(%eax),%edi
lea    0x8(%eax),%edi
lea    0x14(%eax),%edi
lea    0xffffffff(%eax),%edi
lea    0xffffff9c(%ebp),%edi
lea    0xffffffd0(%ebp),%edi
lea    0xffffffd4(%ebp),%edi
lea    0xffffffd8(%ebp),%edi
lea    0xffffffdb(%ebp),%edi
lea    0x4(%esi),%edi
lea    0xff0f3d54(%edx),%eax
lea    0xffffff04(%ebx),%eax
lea    0x805b880(%ebx),%eax
lea    0xfffffd04(%ebp),%eax
lea    0xffffd911(%ebp),%eax
lea    0xfffffd16(%ebp),%eax
lea    0xffffff3c(%ebp),%eax
lea    0xffffff40(%ebp),%eax
lea    0xfffffd68(%ebp),%eax
lea    0xfffffd6c(%ebp),%eax
lea    0xffffff78(%ebp),%eax
lea    0xfffffb9c(%ebp),%eax
lea    0xfffffb9d(%ebp),%eax
lea    0xfffffcec(%ebp),%eax
lea    0xffffeaf2(%ebp),%eax
lea    0x76c(%eax),%ecx
lea    0x76c(%edi,%ecx,1),%ecx
lea    0xffffd911(%ebp),%ecx
lea    0xffffeaf2(%ebp),%ecx
lea    0xfefefeff(%eax),%edx
lea    0x80000000(%ebx),%edx
lea    0xffffff04(%ebx),%edx
lea    0xffffd911(%ebp),%edx
lea    0xffffff3c(%ebp),%edx
lea    0xfffffb9d(%ebp),%edx
lea    0xfffffcec(%ebp),%edx
lea    0x8058972(%edx),%ebx
lea    0x16d(%ebx,%ecx,1),%ebx
lea    0xffffd911(%ebp),%ebx
lea    0xffffdfe8(%ebp),%ebx
lea    0xffffeaf2(%ebp),%ebx
lea    0x0(%esi),%esi
lea    0xfffff92d(%ebp),%esi
lea    0xffffff74(%ebp),%esi
lea    0x0(%esi),%esi
lea    0xffffff04(%ebx),%edi
lea    0x0(%edi),%edi
lea    0xffffeaf2(%ebp),%edi
lea    0x0(%edi),%edi
