#!/bin/sh
#
# @todo
#
#

#
# If TESTING is set to 1, eresi-config will be usable without installing eresi.
# TESTING_ROOT is then the path to your working directory.

TESTING=1

# FIXME: incorrect ! ERESI can be present anywhere, or even already installed
TESTING_ROOT=/home/camoroz0/eresi-0.81-b1-netdebug/

# Those variables are path were eresi headers and libraries were installed.
#

INCDIR=/usr/local/include
LIBDIR=/usr/local/lib

# @todo check if argument is --help
# 
#echo "Usage "

#
# Command lines options for each component without dependancies.
# Dependancies is managed next in the ouput part of the script.

if [ $TESTING = 1 ] ; then
LIBASM_CFLAGS="-I ${TESTING_ROOT}/libasm/include"
LIBASM_DEFINES=
LIBASM_LIBS="-L ${TESTING_ROOT}/libasm/ -lasm32"

LIBASPECT_CFLAGS="-D ERESI32 -I ${TESTING_ROOT}/libaspect/include"
LIBASPECT_DEFINES=
LIBASPECT_LIBS="-L ${TESTING_ROOT}/libaspect/ -laspect32"

LIBELFSH_CFLAGS="-I ${TESTING_ROOT}/libelfsh/include"
LIBELFSH_DEFINES=
LIBELFSH_LIBS="-L ${TESTING_ROOT}/libelfsh/ -lelfsh32"

LIBETRACE_CFLAGS="-I ${TESTING_ROOT}/libetrace/include"
LIBETRACE_DEFINES=
LIBETRACE_LIBS="-L ${TESTING_ROOT}/libetrace/ -letrace32"

LIBMJOLLNIR_CFLAGS="-I ${TESTING_ROOT}/libmjollnir/include"
LIBMJOLLNIR_DEFINES=
LIBMJOLLNIR_LIBS="-L ${TESTING_ROOT}/libmjollnir/ -lmjollnir32"

else

LIBASM_CFLAGS="-D ERESI32 -I ${INCDIR}"
LIBASM_DEFINES=
LIBASM_LIBS="-L ${LIBDIR} -lasm32"

LIBASPECT_CFLAGS="-I ${INCDIR}"
LIBASPECT_DEFINES=
LIBASPECT_LIBS="-L ${LIBDIR} -laspect32"

LIBASPECT_CFLAGS="-I ${INCDIR}"
LIBASPECT_DEFINES=
LIBASPECT_LIBS="-L ${LIBDIR} -lelfsh32"

LIBETRACE_CFLAGS="-I ${INCDIR}"
LIBETRACE_DEFINES=
LIBETRACE_LIBS="-L ${LIBDIR} -letrace32"

LIBMJOLLNIR_CFLAGS="-I ${INCDIR}"
LIBMJOLLNIR_DEFINES=
LIBMJOLLNIR_LIBS="-L ${LIBDIR} -lmjollnir32"

fi

#
# Loop throught arguments
#

while [ "_$1" != "_" ] ; do
    case "$1" in 
    libasm)
    LIBASM=1
    ;;
    libelfsh)
    LIBELFSH=1
    ;;
    libmjollnir)
    LIBMJOLLNIR=1
    ;;

    --libs)
    showLIBS=1
    ;;

    --cflags)
    showCFLAGS=1
    ;;

    --defines)
    showDEFINES=1
    ;;
    esac
    shift 1
done

#
# Print required arguments.
#

##########################################
############ LIBMJOLLNIR ####################

if [ "$LIBMJOLLNIR" = 1 ] ; then
if [ "$showCFLAGS" = 1 ] ; then
	echo ${LIBELFSH_CFLAGS} ${LIBETRACE_CFLAGS} ${LIBASPECT_CFLAGS} ${LIBASM_CFLAGS}  ${LIBMJOLLNIR_CFLAGS} 
fi
if [ "$showLIBS" = 1 ] ; then
	echo ${LIBELFSH_LIBS} ${LIBETRACE_LIBS} ${LIBASPECT_LIBS} ${LIBASM_LIBS}  ${LIBMJOLLNIR_LIBS}
fi
if [ "$showDEFINES" = 1 ] ; then
	echo ${LIBELFSH_DEFINES} ${LIBETRACE_DEFINES} ${LIBASPECT_DEFINES} ${LIBASM_DEFINES} ${LIBMJOLLNIR_DEFINES}
fi
fi

##########################################
############ LIBASM ####################

if [ "$LIBASM" = 1 ] ; then
if [ "$showCFLAGS" = 1 ] ; then
	echo ${LIBELFSH_CFLAGS} ${LIBASPECT_CFLAGS} ${LIBASM_CFLAGS} 
fi
if [ "$showLIBS" = 1 ] ; then
	echo ${LIBELFSH_LIBS} ${LIBASPECT_LIBS} ${LIBASM_LIBS}
fi
if [ "$showDEFINES" = 1 ] ; then
	echo ${LIBELFSH_DEFINES} ${LIBASPECT_DEFINES} ${LIBASM_DEFINES}
fi
fi

##########################################
############ LIBELFSH ####################

if [ "$LIBELFSH" = 1 ] ; then
if [ "$showCFLAGS" = 1 ] ; then
	echo ${LIBELFSH_CFLAGS} ${LIBASPECT_CFLAGS} ${LIBASM_CFLAGS} 
fi
if [ "$showLIBS" = 1 ] ; then
	echo ${LIBELFSH_LIBS} ${LIBASPECT_LIBS} ${LIBASM_LIBS}
fi
if [ "$showDEFINES" = 1 ] ; then
	echo ${LIBELFSH_DEFINES} ${LIBASPECT_DEFINES} ${LIBASM_DEFINES}
fi

fi
