#ifndef __E2DBG-ARM_H__
 #define __E2DBG-ARM_H__

/* ARM registers name */
#define		E2DBG_R0_VAR		"$r0"
#define		E2DBG_R1_VAR		"$r1"
#define		E2DBG_R2_VAR		"$r2"
#define		E2DBG_R3_VAR		"$r3"
#define		E2DBG_R4_VAR		"$r4"
#define		E2DBG_R5_VAR		"$r5"
#define		E2DBG_R6_VAR		"$r6"
#define		E2DBG_R7_VAR		"$r7"
#define		E2DBG_R8_FIQ_VAR	"$r8_fiq"
#define		E2DBG_R9_FIQ_VAR	"$r9_fiq"
#define		E2DBG_R10_FIQ_VAR	"$r10_fiq"
#define		E2DBG_R11_FIQ_VAR	"$r11_fiq"
#define		E2DBG_R12_FIQ_VAR	"$r12_fiq"
#define		E2DBG_R13_USR_VAR	"$r13_usr"
#define		E2DBG_R14_USR_VAR	"$r14_usr"
#define		E2DBG_R13_FIQ_VAR	"$r13_fiq"
#define		E2DBG_R14_FIQ_VAR	"$r14_fiq"
#define		E2DBG_R13_IRQ_VAR	"$r13_irq"
#define		E2DBG_R14_IRQ_VAR	"$r14_irq"
#define		E2DBG_R13_SVC_VAR	"$r13_svc"
#define		E2DBG_R14_SVC_VAR	"$r14_svc"
#define		E2DBG_R13_ABT_VAR	"$r13_abt"
#define		E2DBG_R14_ABT_VAR	"$r14_abt"
#define		E2DBG_R13_UND_VAR	"$r13_und"
#define		E2DBG_R14_UND_VAR	"$r14_und"
#define		E2DBG_CPSR_VAR		"$cpsr"
#define		E2DBG_SPSR_FIQ_VAR	"$spsr_fiq"
#define		E2DBG_SPSR_IRQ_VAR	"$spsr_irq"
#define		E2DBG_SPSR_SVC_VAR	"$spsr_svc"
#define		E2DBG_SPSR_ABT_VAR	"$spsr_abt"
#define		E2DBG_SPSR_UND_VAR	"$spsr_und"

#endif
