##
## Makefile for librevm in ERESI
##
## Started on  Fri Nov  2 16:32:29 2001 jfv
## Updated on  Wed Nov 28 12:57:38 2001 jfv
##

include ../../config.h

all			: all32 all64

all32			: 
			$(MAKE) -C flowjack all32

all64			: 
			$(MAKE) -C flowjack all64

clean		       :
			$(MAKE) -C flowjack clean

fclean		       : clean
		   	$(MAKE) -C flowjack fclean
